authentication/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout
from authentication.forms import LoginForm

app_name='auth'

urlpatterns = [
    url(r'^$', login, {'template_name': 'authentication/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

dashboard/urls.py
from django.conf.urls import url
from dashboard.views import DashboardView

app_name='dashboard'

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

eleven/urls.py
from django.conf.urls import url
from eleven.views import HomeView, AboutView

app_name = 'home'

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^about/$', AboutView.as_view(), name='about'),
]

elevencrypto/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace="auth")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100, default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

dashboard/models.py
from django.db import models

# Create your models here.

eleven/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms
#from captcha.fields import CaptchaField

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'login-input', 'name': 'username'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'login-input', 'name': 'password'}))

class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'signup-input', 'name': 'username'}))
    email = forms.EmailField(max_length=254, required=True, widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'signup-input', 'name': 'email'}))
    first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'signup-input', 'name': 'first_name'}))
    last_name = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'signup-input', 'name': 'last_name'}))
    password1 = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'signup-input', 'name': 'password'}))
    password2 = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password', 'class': 'signup-input', 'name': 'repeat_password'}))
    #captcha = CaptchaField()

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

authentication/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from authentication.forms import SignupForm
from django.urls import reverse

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('auth:login'))
        else:
            return render(request, 'authentication/signup.html', {'form': form})
    else:
        form = SignupForm()

        args = {'form': form}
        return render(request, 'authentication/signup.html', args)

dashboard/views.py
from django.views.generic import TemplateView
#from fusioncharts import FusionCharts

class DashboardView(TemplateView):
    template_name = 'dashboard/dashboard.html'

eleven/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomeView(TemplateView):
	template_name = 'eleven/home.html'

class AboutView(TemplateView):
	template_name = 'eleven/about.html'

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
  <title>ElevenCrypto | Login</title>
{% endblock %}
{% block body %}
<div id="imageSlider" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <!-- IMAGE 1 -->
    <div class="item active">
      <div class="parallax-window info-image" data-parallax="scroll" data-iosFix="true" data-image-src="{% static 'eleven/home-img/mountains.png' %}"></div>
      <div class="carousel-caption">
        <div class="login-container">
          <h1>Login</h1>
          <form class="login-form" method="post">
            {% csrf_token %}
            <p>{{ form.username }}</p>
            <p>{{ form.password }}</p>
            {% if form.errors %}
              <p class="error">Your username and password didn't match. Please try again.</p>
            {% endif %}
            <p class="login-p"><a href="#">Lost your password?</a></p>
            <button class="btn btn-default login-button" type="submit"><i id="login-icon" class="fa fa-sign-in" aria-hidden="true"></i> Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'base.html' %}

{% block head %}
  <title>ElevenCrypto | Signup</title>
{% endblock %}
{% block body %}
  <div class="container text-center">
    <div class="signup-container">
      <h1>Signup</h1>
      <form class="login-form" method="post">
        {% csrf_token %}
        <p>{{ form.username }}</p>
        <p>{{ form.email }}</p>
        <p>{{ form.first_name }}</p>
        <p>{{ form.last_name }}</p>
        <p>{{ form.password1 }}</p>
        <p>{{ form.password2 }}</p>
        <!--<p>{{ form.captcha }}</p>-->
        <button class="btn btn-default signup-button" type="submit"><i id="signup-icon" class="fa fa-chevron-circle-up" aria-hidden="true"></i> Signup</button>
      </form>
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
  <title>ElevenCrypto | Dashboard</title>
  <script src="{% static 'dashboard/fusioncharts/fusioncharts.js' %}" type="text/javascript"></script>
{% endblock %}
{% block body %}
  <div class="dashboard-container">
    <nav class="navbar-primary">
      <span class="glyphicon glyphicon-user user-icon"></span>
      <h4>Welcome Back</h4>
      <a href="#" class="btn-expand-collapse"><span class="glyphicon glyphicon-menu-left"></span></a>
      <ul class="navbar-primary-menu">
        {% url 'dashboard:dashboard' as url %}
        <li {% if request.path == url %} class="active" {% endif %}><a href="{% url 'dashboard:dashboard' %}"><span class="glyphicon glyphicon-th-large"></span><span class="nav-label">Dashboard</span></a></li>
        <li><a href="#"><span class="glyphicon glyphicon-tasks"></span><span class="nav-label">Allocation</span></a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle='dropdown' href="#"><span class="glyphicon glyphicon-cog"></span><span class="nav-label">My Account</span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Settings</a></li>
            <li><a href="#">Affiliate</a></li>
            <li><a href="#">Customer Service</a></li>
          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-list"></span><span class="nav-label">My Orders</span></a></li>
        <li><a href="#"><span class="glyphicon glyphicon-flash"></span><span class="nav-label">Buy Hashpower</span></a></li>
      </ul>
      {% if user.is_staff %}
      <span class="glyphicon glyphicon-eye-open admin-icon"></span>
      <h4>Admin Manager</h4>
      <ul class="navbar-primary-menu admin">
        <li><a href="/admin"><span class="glyphicon glyphicon-sunglasses"></span><span class="nav-label">Admin</span></a></li>
      </ul>
      {% endif %}
    </nav>
    <div class="dashboard-content">
      <div class="hashpower-display">
        <span class="glyphicon glyphicon-hdd hashpower-icon"></span>
        <h3>0.0000 MH/s</h3>
        <hr width=90%>
        <h3>Ether</h3>
        <h4>Hashrate</h4>
      </div>
      <div class="widget-container">
        <div class="section-block">
          <span class="glyphicon glyphicon-tasks block-icon"></span>
          <h4>Mining Allocation</h4>
          <p>Allocate your hashpower</p>
          <button class="btn btn-default alloc-button" type="button"><span class="glyphicon glyphicon-signal button-icon"></span>Configure Miners</button>
        </div>
        <div class="section-block">
          <span class="glyphicon glyphicon-flash block-icon"></span>
          <h4>Buy Hashpower</h4>
          <p>Purchase more hashpower</p>
          <button class="btn btn-default alloc-button" type="button"><span class="glyphicon glyphicon-flash button-icon"></span>Buy Hashpower</button>
        </div>
      </div>
    </div>
  </div>

  {% block footer %}
  {% endblock %}

{% block javascript %}
  <script type="text/javascript">
    $('.btn-expand-collapse').click(function(e) {
          $('.navbar-primary').toggleClass('collapsed');
    });
  </script>
{% endblock %}
{% endblock %}

eleven/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    <title>ElevenCrypto Base</title>
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Raleway" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'eleven/js/parallax.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'eleven/main.css' %}" type=" text/css">
    <link rel="shortcut icon" type="image/png" href="{% static 'eleven/home-img/favicon/favicon.ico' %}">
  </head>
  <body>
    <!-- TOP NAVIGATION -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="logo-container navbar-left web-logo" href="{% url 'auth:login' %}"><img class="logo img-responsive" src="{% static 'eleven/home-img/logo-side.png' %}"/></a>
          <a class="logo-container navbar-left mobile-logo" href="{% url 'auth:login' %}"><img class="logo img-responsive" src="{% static 'eleven/home-img/logo2.png' %}"/></a>
        </div>
        <div class="collapse navbar-collapse" id="mobileNavbar">
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><i id="bell-icon" class="fa fa-bell-o" aria-hidden="true"></i></i></a></li>
            <li><a href="{% url 'auth:logout' %}"><i id="power-off-icon" class="fa fa-power-off" aria-hidden="true"></i></a></li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- END TOP NAVIGATION -->
    {% block body %}
      <h1>Base Block</h1>
    {% endblock %}

    {% block footer %}
    <!-- FOOTER -->
    <footer class="container-fluid text-center">
      <div class="row">
        <div class="col-sm-4">
          <a href="{% url 'auth:login' %}"><img class="logo-footer img-responsive" src="{% static 'eleven/home-img/logo-side.png' %}"/></a>
        </div>
        <div class="col-sm-4">
          <h3>Support</h3>
          <ul class="nav footer-nav">
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h3>Connect With Us</h3>
          <a href="https://www.facebook.com/Eleven-Crypto" class="fa fa-facebook"></a>
          <a href="https://twitter.com/ElevenCrypto" class="fa fa-twitter"></a>
          <a href="https://www.instagram.com/elevencrypto" class="fa fa-instagram"></a>
        </div>
      </div>
    </footer>
    <!-- END FOOTER -->
    {% endblock %}
  </body>
</html>

eleven/templates/eleven/about.html
{% extends 'base.html' %}

{% block head %}
  <title>ElevenCrypto | About Us</title>
{% endblock %}
{% block body %}
{% load static %}
<div class="container text-center about-container">
    <h1>About Us</h1>
    <p class="text-center about-text">
      Eleven was founded in 2016 by crypto-enthusiast. That hobby has turned into
      the largest cloud mining service in the Midwest. We offer our clients the
      exciting experience of mining digital-currencies without the hassle. Our
      ambitious team is dedicated to bringing our customers the highest level of
      satisfaction. We all love and believe in this amazing technology, and we
      are here to help you become a part of it!
    </p>
    <img class="img-responsive team-img" src="{% static 'eleven/home-img/bg-3.png' %}">
    <div class="row profile">
      <div class="col-sm-4">
        <div class="parallax-window profile-icon" data-parallax="scroll" data-image-src="{% static 'eleven/home-img/profile-icon.png' %}">
          <div class="hidden-profile">
            <h3>Trey Hamilton</h3>
            <h5>CEO ElevenCrypto / Co-founder</h5>
            <br>
            <p>Early Bitcoin investor / Miner</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="parallax-window profile-icon" data-parallax="scroll" data-image-src="{% static 'eleven/home-img/profile-icon.png' %}">
          <div class="hidden-profile">
            <h3>Chris Filardo</h3>
            <h5>Co-founder ElevenCrypto</h5>
            <br>
            <p>Sales</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="parallax-window profile-icon" data-parallax="scroll" data-image-src="{% static 'eleven/home-img/profile-icon.png' %}">
          <div class="hidden-profile">
            <h3>Zach Amrein</h3>
            <h5>CTO ElevenCrypto</h5>
            <br>
            <p>ElevenCrypto Developer</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

eleven/templates/eleven/home.html
{% extends 'base.html' %}

{% block head %}
  <title>ElevenCrypto</title>
{% endblock %}
{% block body %}
{% load static %}
<!-- IMAGE SLIDER -->
  <div id="imageSlider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <!-- IMAGE 1 -->
      <div class="item active">
        <div class="parallax-window info-image" data-parallax="scroll" data-iosFix="true" data-image-src="{% static 'eleven/home-img/mountains.png' %}"></div>
        <div class="carousel-caption">
          <h3>Join the largest cloud mining service in the world</h3>
          <h1 class="text-uppercase big">Start Mining Today!</h1>
          <hr width="50%" />
          <br>
          <button type="button" class="btn btn-default top-btn">Start Mining</button>
          <button type="button" class="btn btn-default">Learn More</button>
        </div>
      </div>
    </div>
  </div>
<!-- END IMAGE SLIDER -->

<!-- SECTION 1 -->
  <div class="container-fluid text-center section1">
    <div class="top-section">
      <img class="icon4" src="{% static 'eleven/home-img/icons/icon4.png' %}" alt="">
      <h2>Welcome to the largest cloud mining service in the Midwest</h2>
      <h4>We are currently only filling Ethereum (ETH) contracts. More coins coming soon!</h4>
      <hr width="50%" />
      <h1>Get your first 100 MH/s Here!</h1>
    </div>
    <div class="ether-container">
        <div class="ether-plan">
          <h2 class="bold">Small Plan</h2>
          <p class="text-center">Starter</p>
          <h1 class="bold price">$30.00</h1>
          <hr>
          <h3>5 MH/s</h3>
          <hr>
          <p class="text-center">1 Year Ethereum Mining*</p>
          <p class="text-center">No Maintenance Cost</p>
          <button type="button" class="btn btn-default active-btn">Create Small Plan</button><br>
          <button type="button" class="btn btn-default btn-black">Plan Details</button>
        </div>
        <div class="ether-plan">
          <h2 class="bold">Medium Plan</h2>
          <p class="text-center">Best Buy</p>
          <h1 class="bold price">$869.00</h1>
          <hr>
          <h3>40 MH/s</h3>
          <hr>
          <p class="text-center">1 Year Ethereum Mining*</p>
          <p class="text-center">No Maintenance Cost</p>
          <button type="button" class="btn btn-default active-btn">Create Medium Plan</button><br>
          <button type="button" class="btn btn-default btn-black">Plan Details</button>
        </div>
        <div class="ether-plan">
          <h2 class="bold">Large Plan</h2>
          <p class="text-center">Max Profit</p>
          <h1 class="bold price">$2999.00</h1>
          <hr>
          <h3>100 MH/s</h3>
          <hr>
          <p class="text-center">1 Year Ethereum Mining*</p>
          <p class="text-center">No Maintenance Cost</p>
          <button type="button" class="btn btn-default active-btn">Create Large Plan</button><br>
          <button type="button" class="btn btn-default btn-black">Plan Details</button>
        </div>
        <div class="ether-plan">
          <h2 class="bold">Custom Plan</h2>
          <p class="text-center">Create a custom mining plan</p>
          <h1 class="bold price">$0.00</h1>
          <hr>
          <h3>0 MH/s</h3>
          <hr>
          <p class="text-center">Your Own Custom Plan*</p>
          <p class="text-center">No Maintenance Cost</p>
          <button type="button" class="btn btn-default active-btn">Create Custom Plan</button><br>
          <button type="button" class="btn btn-default btn-black">Plan Details</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END SECTION 1 -->

<!-- SECTION 2 -->
<div class="container-fluid text-center section2">
  <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'eleven/home-img/bg-1.png' %}">
    <div class="row info-image-pad">
      <div class="col-lg-6">
        <img src="{% static 'eleven/home-img/icons/icon6.png' %}" alt="">
        <h1 class="text-uppercase">Why Choose Us?</h1>
        <p class="text-center">
           We are an American based cloud mining service.
           Eleven offers you a new safe and savvy way to invest your money in
           digital-currencies. Our team is uniquely comprised of crypto-experts
           who have combined years of experience in every aspect of this industry.
           We started this company after realizing the value of the technology
           surrounding the blockchain; and how difficult and costly it was for an
           average user to buy, build, code, and house a crypto-miner. We believe
           that every person should have the opportunity to mine regardless of their
           knowledge and resources. That is why we provide a transparent service to help
           grow this amazing community. Our goal is to bring the power of mining to you!
        </p>
      </div>
      <div class="col-lg-6">
        <img src="{% static 'eleven/home-img/icons/icon1.png' %}" alt="">
        <h1 class="text-uppercase">Competitive Pricing</h1>
        <p class="text-center">
           If you’ve done research on crypto-mining then you understand that
           hardware prices are surging and there is currently a shortage of
           mining equipment. We offer the best hashing power to hardware and
           electricity cost around. The resources and partnerships Eleven
           has created over the years are phenomenal and give us the ability
           to offer these prices. When you sign a contract with Eleven you are
           purchasing more than just hashing power, you are also purchasing the
           access of our resources, network and crypto-expertise.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- END SECTION 2 -->

<!-- SECTION 3 -->
<div class="container-fluid text-center section3 padding-eleven">
  <h1>The Eleven Mining Experience</h1>
  <div class="row">
    <div class="col-lg-6">
      <h4 class="padding-h4">
          The sense of empowerment and innovation mining gives us is what drives
          our company to do this, and our goal is to share this feeling with our
          customers as well. This experience will be transparent, and you will be
          included in every decision-making step of the way.
      </h4>
    </div>
    <div class="col-lg-6">
      <h4 class="padding-h4">
          Mining is the creation of crypto-currency. Once you decide to sign with
          Eleven you are officially a crypto-miner; you are now at the forefront of
          crypto-creation. We eliminate the stress of:
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon5.png' %}">
      <h4>Mining Equiptment Shortages</h4>
    </div>
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon13.png' %}">
      <h4>Constant Maintenance</h4>
    </div>
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon8.png' %}">
      <h4>A Persistent, Obnoxious Humming Noise</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon10.png' %}">
      <h4>Heat Generated From Mining Servers</h4>
    </div>
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon11.png' %}">
      <h4>Cost Prohibitive Electricity Accommodations</h4>
    </div>
    <div class="col-sm-4 eleven-icon-padding">
      <img src="{% static 'eleven/home-img/icons/icon12.png' %}">
      <h4>Storage</h4>
    </div>
  </div>
</div>
<!-- END SECTION 3 -->
{% endblock %}